### ISSUE TITLE
When I reload my UI this happens

### ISSUE THREAD

**Issue by Larsy93** [Geigerkind/VCB#12]
https://i.gyazo.com/4e656cf99ff55ae41ddb49e74e7f26f2.jpg

It sort of goes into the anchor mode but with wrong colors and i cant move them around. Only way to solve it is so disable the addon or do a full relog, got any idea what it might be?

**Comment by tdymel** [comment]
Hey!
I can not reproduce this :<

**Comment by Hallonkaka** [comment]
I get the same problem

https://gyazo.com/f0455c0607dd1cae35b15a0fc8df64e0

**Comment by Larsy93** [comment]
Ok. maybe we are on way to a solution now that we have .lua errors. Thanks for the addition

**Comment by tdymel** [comment]
So, does this happen everytime you guys reload the ui?
Could you maybe disable one addon after each other to find out if another addon is causing it?

**Comment by Larsy93** [comment]
Everytime, it used to work but stopped working

Den 15 jan. 2017 10:21 em skrev "Tom Dymel" <notifications@github.com>:

So, does this happen everytime you guys reload the ui?
Could you maybe disable one addon after each other to find out if another
addon is causing it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Geigerkind/VCB/issues/12#issuecomment-272724683>, or mute
the thread

**Comment by tdymel** [comment]
Should be fixed now

**Comment by Larsy93** [comment]
Still the same problem sadly :(

**Comment by Larsy93** [comment]
works on login but when i reload ui or go through a loading screen it breaks.

**Comment by tdymel** [comment]
Alright. If you can reproduce it, could you please deactivate one addon after each other to see if any is causing it.

Or, first disable all but VCB (And Ace libs obv) and try if reload works then, and then check which addon might cause it?

cheers!

**Comment by tdymel** [comment]
Guess I will close it, if it is just some addon conflict, if you can't tell me which one is causing it

**Comment by Larsy93** [comment]
Sorry I was away, it happens on my shaman with only VCB enabled, on my rogue it seems to work perfectly tho, with all my addons enabled, I have tried removing my WTF folder and starting with a fresh one, still get the same problem.

**Comment by Larsy93** [comment]
https://i.gyazo.com/c93abd7653b871903a2c5f33e3932d44.jpg
