### ISSUE TITLE
[Request] Ability to change aura text location

### ISSUE THREAD

**Issue by WashingMachine** [Geigerkind/VCB#14]
Hello,

First of all, thank you for all your hard work for all of us to enjoy your addon, much appreciated 👍
My request is this:
Is there anyway you can let us choose the placement of the aura timer?
What I would love to do is use your buff frame on a left to right orientation (right above my char unit frame) and be able to place the aura timer on top (instead of bottom as is the only position we can put it right now)

**Comment by tdymel** [comment]
Implemented it in the next update
