### ISSUE TITLE
Timer-Bug

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/VCB#16]
find a small bug, see in the pic > http://www.bilder-upload.eu/show.php?file=210c9f-1486220463.jpg

in addition: How can i change the Weapondirection? so that i have MH/OH? aktually it is OH/MH and i found no Option zu change this ;)

Thanks Mixus

**Comment by tdymel** [comment]
This is more or less intended. I increased the size from left to right, just try to adjust the font size or choose the modifiers differently.

I am afraid that there is no option, or try reversing the order.

**Comment by Mixuspidelix** [comment]
ok, ich muss zugeben, ich hab keinen Plan wie ich die Icons wechseln kann ^^ Hab leider 0 Plan von Lua :D 
Vielleicht würdest Du mir da nochmal unter die Arme greifen? Hätte Dir auch ne Pm geschrieben, leider weiss ich nicht ob das hier auf Github überhaupt geht. Denn, gefunden hab ich es net. :s 

Mfg der Mixus

**Comment by tdymel** [comment]
Wenn du das Consolidated Icon meinst, ersetze einfach die Datei im images ordner mit einer Grafik die Wow kompatibel ist.

**Comment by Mixuspidelix** [comment]
Hier mal nen Bild was ich meine ^^ http://www.bilder-upload.eu/show.php?file=87e46b-1487597753.jpg Bilder sagen ja meist mehr als tausend Worte :D

**Comment by tdymel** [comment]
wenn ich nicht irgendwo ne invertier funktion eingebaut habe, dann geht das nicht

**Comment by Mixuspidelix** [comment]
also gefunden hab ich keine. Schade :( ist noch mit das einzige was mich etwas stört, da ich meist verplane meine Gifte zu erneuern - bin es gewohnt andersrum zu sehen ^^

**Comment by tdymel** [comment]
Hab mal eine option hinzugefügt, cheers!
