### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Monteo** [Geigerkind/VCB#17]
![wowscrnshot_020617_235256](https://cloud.githubusercontent.com/assets/24656088/22694773/0de5a76e-ed7b-11e6-882b-c7f2329b60db.jpg)
![wowscrnshot_020617_235406](https://cloud.githubusercontent.com/assets/24656088/22694774/0e0d3374-ed7b-11e6-875a-06fcea2d2c9d.jpg)

**Comment by tdymel** [comment]
How can I reproduce it?

**Comment by Monteo** [comment]
I just ordered /reloadui

**Comment by tdymel** [comment]
Can you check if this still happens with all addons deactivated but VCB?
If so, please also gradually check which addon causes it.
I have the feeling that some addon is causing it because I can't reproduce it.
cheers!

Edit: Alternativly upload your interface folder here

**Comment by Monteo** [comment]
http://rgho.st/7B7LHPDk8
http://dropmefiles.com/gTuB9

**Comment by Monteo** [comment]
I think it is not because of add-ons.
I smeared poison on weapons.
When I remove the weapon in your inventory error does not appear
I came to this with the included only VCB

**Comment by tdymel** [comment]
ah ok, will investigate it, thanks!

**Comment by tdymel** [comment]
Thanks that was it!
