### ISSUE TITLE
once again ^^

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/VCB#18]
http://www.bilder-upload.eu/show.php?file=fb21e0-1487339828.jpg and the Bufftimers are overlapping.

mfg Mixus 

Ps: kann ich eigentlich Dir auch auf Deutsch schreiben? Mein Englisch ist net das beste :P

**Comment by tdymel** [comment]
Klar.
Ja, dann musst du das Padding der Auren verändern oder den Font kleiner machen^^
Da kann ich nicht mehr tun^^

**Comment by Mixuspidelix** [comment]
Na bei den Debuff-Timer gibt es noch ein Problem. Das Gleiche welches es zuvor bei den Buff-Timer gab. Schau Dir das Bild nochmal an, bitte :) Das hat nix mit dem überlappen zu tuen,. Das war eine Extra Frage gewesen welche ich mit der Verkleinerung der Timergröße gut bereinigen konnte ;)

Danke der Mixus

Edit meint: Hinter den Zahlen erscheinen wieder diese ...

**Comment by tdymel** [comment]
Fixed
