### ISSUE TITLE
localization: translations for koKR  done!

### ISSUE THREAD

**Issue by godtanker** [Geigerkind/VCB#20]
if (GetLocale() == "koKR") then	
    VCB_MAIN_NAME = "VCB 버프/디버프 확장프레임"
	VCB_MAIN_VERSION = "v4.0"
	VCB_MINIMAP_TOOLTIP_NAME = "VCB 버프/디버프 확장프레임"
	VCB_MINIMAP_TOOLTIP_LEFTCLICK = "좌클릭: 토글옵션메뉴"
	VCB_MINIMAP_TOOLTIP_RIGHTCLICK = "우클릭 : 버프프레임 잠금 토글모드"
	VCB_MINIMAP_TOOLTIP_DRAG = "드레그 : 미니맵아이콘 이동"
	VCB_TOP_BUTTON_CLOSE = "구성 프레임 닫기"
	VCB_TOP_BUTTON_LOCK = "VCB 잠그기"
	VCB_TOP_BUTTON_MINIMAP = "미니맵 버튼 보기/가리기"
	VCB_TOP_BUTTON_DUMMY = "버프프레임 보기/가리기"
	VCB_MENU_HEAD = "메뉴"
	VCB_MENU_BUTTON1_LINK = "통합 버프"
	VCB_MENU_BUTTON1_NAME = "통합 버프"
	VCB_MENU_BUTTON2_LINK = "차단된 버프"
	VCB_MENU_BUTTON2_NAME = "차단된 버프"
	VCB_MENU_BUTTON3_LINK = "시간표시"
	VCB_MENU_BUTTON3_NAME = "시간표시"
	VCB_MENU_BUTTON4_LINK = "통합 프레임 -1-"
	VCB_MENU_BUTTON4_LINK2 = "통합 프레임 -2-"
	VCB_MENU_BUTTON4_NAME = "통합 프레임"
	VCB_MENU_BUTTON5_LINK = "버프 프레임 -1-"
	VCB_MENU_BUTTON5_LINK2 = "버프 프레임 -2-"
	VCB_MENU_BUTTON5_NAME = "버프 프레임"
	VCB_MENU_BUTTON6_LINK = "디버프 프레임 -1-"
	VCB_MENU_BUTTON6_LINK2 = "디버프 프레임 -2-"
	VCB_MENU_BUTTON6_NAME = "디버프 프레임"
	VCB_MENU_BUTTON7_LINK = "무기버프 프레임 -1-"
	VCB_MENU_BUTTON7_NAME = "무기버프 프레임"
	VCB_MENU_BUTTON8_LINK = "프로파일 매니져"
	VCB_MENU_BUTTON8_NAME = "프로파일 매니져"
	VCB_MENU_BUTTON9_LINK = "기타 사항"
	VCB_MENU_BUTTON9_NAME = "기타 사항"
	VCB_MENU_BUTTON10_LINK = "VCB에 대해"
	VCB_MENU_BUTTON10_NAME = "VCB에 대해"
	VCB_CONFIG_FRAME_TITLE_ONLOAD = "통합 버프"
	VCB_CB_BB_FRAME_LEFT_INSERT = "버프 이름 입력:"
	VCB_CB_BB_FRAME_LEFT_DELETE = "선택된 버프:"
	VCB_CB_BB_FRAME_LEFT_ADD = "우측 버프슬롯에 추가"
	VCB_CB_BB_FRAME_LEFT_DELETE_BUTTON = "선택된 버프 지우기"
	VCB_CB_BB_FRAME_LEFT_RA = "모두 제거"
	VCB_TIMER_FRAME_SHOW_HOURS = "시간 표시"
	VCB_TIMER_FRAME_SHOW_HOURS_TOOLTIP = "3600초 이상 남아 있는 경우 타이머를 시간 형식으로 지정하려면이 옵션을 선택하십시오."
	VCB_TIMER_FRAME_SHOW_HOURS_CONVERT = "시간과 분 표시(h:m)"
	VCB_TIMER_FRAME_SHOW_HOURS_CONVERT_TOOLTIP = "시간과 분을 모두 표시하려면이 옵션을 선택하십시오. 예 : 1:34h."
	VCB_TIMER_FRAME_SHOW_MINUTES = "분 표시"
	VCB_TIMER_FRAME_SHOW_MINUTES_TOOLTIP = "60초가 넘는 경우 타이머를 분 단위로 포맷하려면 이 옵션을 선택하십시오."
	VCB_TIMER_FRAME_SHOW_MINUTES_CONVERT = "분과 초 표시(m:s)"
	VCB_TIMER_FRAME_SHOW_MINUTES_CONVERT_TOOLTIP = "분과 초를 모두 표시하려면 이 옵션을 선택하십시오. 예 : 10:24m."
	VCB_TIMER_FRAME_SHOW_TENTH = "마지막 60초를 소수점 두자리까지 표시." --Show tenth the last 60 seconds
	VCB_TIMER_FRAME_SHOW_TENTH_TOOLTIP = "초단위 소수점 두자리 까지 표시하려면이 항목을 선택하십시오. 예 : 10:44s."
	VCB_TIMER_FRAME_ROUND_DOWN = "반 내림" --Round down
	VCB_TIMER_FRAME_ROUND_DOWN_TOOLTIP = "타이머를 반 내림하려면 이 항목을 선택하십시오. 예 : 70s->1m."
	VCB_TIMER_FRAME_ROUND_UP = "반 올림"
	VCB_TIMER_FRAME_ROUND_UP_TOOLTIP = "타이머를 반 올림하려면 이 옵션을 선택하십시오. 예 : 70s->2m."
	VCB_TIMER_FRAME_FLASH = "버프 만료시 깐박임 사용"
	VCB_TIMER_FRAME_FLASH_TOOLTIP = "버프가 만료 될 때 깐박임을 사용하려면 이 옵션을 선택하십시오(30초)."
	VCB_TIMER_FRAME_COLOR_BELOW_60 = "60초 미만 색상 변경"
	VCB_TIMER_FRAME_COLOR_BELOW_60_TOOLTIP = "버프가 60초 미만일때 색을 변경하려면 이 옵션을 선택하십시오."
	VCB_CF_FRAME_POSSIBLE_BUFFS = "통합버프아이콘의 많은 양의 버프를 보여 줌."
	VCB_CF_FRAME_POSSIBLE_BUFFS_TOOLTIP = "이 옵션을 선택하면 통합 할 수있는 통합버프아이콘에 보유하고있는 버프를 표시합니다."
	VCB_CF_FRAME_SHOW_PB_GRAYED_OUT = "누락 된 버프 표시 (회색으로 표시됨)"
	VCB_CF_FRAME_SHOW_PB_GRAYED_OUT_TOOLTIP = "통합되었을 수있는 누락 된 버프를 표시하려면이 항목을 선택하십시오."
	VCB_CF_FRAME_ICON_OPACITY = "통합버프아이콘 불투명도"
	VCB_CF_FRAME_ICON_OPACITY_TOOLTIP = "이 커서를 움직여 통합버프 아이콘의 불투명도를 변경합니다."
	VCB_CF_FRAME_ICON_TEXTURE = "텍스쳐"
	VCB_CF_FRAME_ICON_TEXTURE_TOOLTIP = "이 커서를 이동하여 아이콘 텍스처를 변경하십시오."
	VCB_CF_FRAME_BF_ANCHOR = "축" --Anchor
	VCB_CF_FRAME_BF_ANCHOR_TOOLTIP = "이 커서를 움직여 통합버프창의 축을 변경하십시오."
	VCB_CF_FRAME_BF_BACKGROUND = "백그라운드"
	VCB_CF_FRAME_BF_BACKGROUND_TOOLTIP = "이 커서를 움직여 버프의 배경 텍스처를 변경하십시오."
	VCB_CF_FRAME_BF_CUSTOM_BACKGROUND_PATH = "사용자 정의 배경 경로:"
	VCB_DBF_FRAME_COLOR_NONE = "없음"
	VCB_DBF_FRAME_COLOR_NONE_TOOLTIP = "불특정 디버프가 있는 경우 여기를 클릭하여 테두리 색상을 변경하십시오."
	VCB_DBF_FRAME_COLOR_POISON = "독"
	VCB_DBF_FRAME_COLOR_POISON_TOOLTIP = "독이 지정된 디버프가 있는 경우 디버프의 테두리의 색깔을 바꾸려면 여기를 클릭하십시오."
	VCB_DBF_FRAME_COLOR_MAGIC = "마법"
	VCB_DBF_FRAME_COLOR_MAGIC_TOOLTIP = "마법으로 지정된 디버프가 있는 경우 여기를 클릭하여 테두리 색상을 변경하십시오."
	VCB_DBF_FRAME_COLOR_CURSE = "저주"
	VCB_DBF_FRAME_COLOR_CURSE_TOOLTIP = "저주가 지정된 디버프가 있는 경우 테두리색상을 변경하려면 여기를 클릭하십시오."
	VCB_DBF_FRAME_COLOR_DISEASE = "질병"
	VCB_DBF_FRAME_COLOR_DISEASE_TOOLTIP = "질병이 지정된 디버프가 있는 경우 테두리색상을 변경하려면 여기를 클릭하십시오."
	VCB_WP_FRAME_ATTACH_TO_BF_FRAME = "무기버프를 버프 프레임에 부착"
	VCB_WP_FRAME_ATTACH_TO_BF_FRAME_TOOLTIP = "무기 프레임을 버프 프레임에 부착하려면 이 옵션을 선택하십시오. 무기 프레임은 버프 프레임 오라로서 취급됩니다."
	VCB_PM_FRAME_LEFT_INSERT_TEXT = "이름 입력:"
	VCB_PM_FRAME_LEFT_SELECT_TEXT = "선택한 프로필:"
	VCB_PM_FRAME_LEFT_CURRENT_TEXT = "현재 프로필:"
	VCB_PM_FRAME_LEFT_SAVE_TEXT = "저장"
	VCB_PM_FRAME_LEFT_DELETE_TEXT = "삭제"
	VCB_MISC_FRAME_TEXT_DISABLE_CF = "통합버프 아이콘 가리기"
	VCB_MISC_FRAME_TEXT_DISABLE_CF_TOOLTIP = "통합버프 아이콘을 사용하지 않으려면 이 옵션을 선택하십시오. 프레임은 고급 옵션이있는 일반 버프 프레임처럼 작동합니다."
	VCB_MISC_FRAME_TEXT_DISABLE_BB = "메카닉 금지 사용 안 함" --Disable banning mechanic
	VCB_MISC_FRAME_TEXT_DISABLE_BB_TOOLTIP = "매카닉 금지를 사용하지 않으려면 이 옵션을 선택하십시오." --Check this to disable the banning mechanic.
	VCB_MISC_FRAME_TEXT_THEME = "테마"
	VCB_MISC_FRAME_TEXT_THEME_TOOLTIP = "테마를 변경하려면 이 단추를 움직입니다. 테마를 로드하려면 옆에있는 버튼을 클릭하십시오."
	
	VCB_COMMON_COLOR_FONTCOLOR = "글꼴 색상 선택"
	VCB_COMMON_COLOR_FONTCOLOR_TOOLTIP = "글꼴의 색상을 변경하려면 여기를 클릭하십시오."
	VCB_COMMON_COLOR_BORDERCOLOR = "테두리 색 선택을 클릭하십시오."
	VCB_COMMON_COLOR_BORDERCOLOR_TOOLTIP = "테두리 색상을 변경하려면 여기를 클릭하십시오."
	VCB_COMMON_COLOR_BACKGROUNDCOLOR = "배경색 선택"
	VCB_COMMON_COLOR_BACKGROUNDCOLOR_TOOLTIP = "배경색상을 변경하려면 여기를 클릭하십시오."
	
	VCB_COMMON_BUTTON_ENABLE_FONT_BORDER = "글꼴 테두리"
	VCB_COMMON_BUTTON_ENABLE_FONT_BORDER_TOOLTIP = "글꼴 아웃라인을 확인하십시오."
	VCB_COMMON_BUTTON_INVERT_ORDER = "순서 반전"
	VCB_COMMON_BUTTON_INVERT_ORDER_TOOLTIP = "버프 주문을 반전하려면이 옵션을 선택하십시오."
	VCB_COMMON_BUTTON_USE_CUSTOM_BORDER = "사용자 정의 테두리 사용"
	VCB_COMMON_BUTTON_USE_CUSTOM_BORDER_TOOLTIP = "사용자정의 테두리를 사용하려면 이 옵션을 선택하십시오."
	VCB_COMMON_BUTTON_USE_CUSTOM_BACKGROUND = "사용자정의 배경 사용"
	VCB_COMMON_BUTTON_USE_CUSTOM_BACKGROUND_TOOLTIP = "사용자정의 배경을 사용하려면 이 옵션을 선택하십시오."
	VCB_COMMON_BUTTON_ENABLE_BORDER = "테두리 사용"
	VCB_COMMON_BUTTON_ENABLE_BORDER_TOOLTIP = "테두리를 추가하려면 이 옵션을 선택하십시오."
	VCB_COMMON_BUTTON_ENABLE_BACKGROUND_COLOR = "배경색 사용"
	VCB_COMMON_BUTTON_ENABLE_BACKGROUND_COLOR_TOOLTIP = "아이콘에 배경색을 추가하려면 이 옵션을 선택하십시오."
	VCB_COMMON_BUTTON_VERTICAL_MODE = "수직 모드"
	VCB_COMMON_BUTTON_VERTICAL_MODE_TOOLTIP = "이것을 확인하여 프레임을 수직 모드로 전환하십시오."
	VCB_COMMON_BUTTON_INVERT_ORIENTATION = "오라 방향을 반대로" --Invert aura orientation
	VCB_COMMON_BUTTON_INVERT_ORIENTATION_TOOLTIP = "오라 방향을 반대로하려면이 옵션을 선택하십시오. 버프가 오른쪽 대신에 왼쪽에 놓여 있다는 것을 의미합니다."
	VCB_COMMON_BUTTON_CUSTOMFONT = "사용자정의 글꼴"
	VCB_COMMON_BUTTON_CUSTOMFONT_TOOLTIP = "기본설정된 글꼴 대신 사용자정의 글꼴을 사용하십시오."
	
	VCB_COMMON_BUTTON_LOAD_TEXT = "불러오기"
	
	VCB_COMMON_SLIDER_FONT_SIZE = "폰트 사이즈"
	VCB_COMMON_SLIDER_FONT_SIZE_TOOLTIP = "글꼴 크기를 변경하려면이 커서를 좌우로 움직이세요."
	VCB_COMMON_SLIDER_FONT = "폰트"
	VCB_COMMON_SLIDER_FONT_TOOLTIP = "이 글꼴을 변경하려면 커서를 이동하십시오."
	VCB_COMMON_SLIDER_FONT_OPACITY = "폰트 불투명도"
	VCB_COMMON_SLIDER_FONT_OPACITY_TOOLTIP = "불투명도를 변경하려면이 값을 움직입니다."
	VCB_COMMON_SLIDER_SCALE = "크기"
	VCB_COMMON_SLIDER_SCALE_TOOLTIP = "이 커서를 좌우로 움직여 통합버프아이콘창의 폰트크기를 변경 하십시오."
	VCB_COMMON_SLIDER_BUFFS_PER_ROW = "행당(세로) 버프 수" --Buffs per row
	VCB_COMMON_SLIDER_BUFFS_PER_ROW_TOOLTIP = "통합버프아이콘창의 행당(세로)버프수를 변경하십시오."
	VCB_COMMON_SLIDER_BACKGROUND_OPACITY = "배경 불투명도"
	VCB_COMMON_SLIDER_BACKGROUND_OPACITY_TOOLTIP = "커서를 움직여 배경의 불투명도를 변경하십시오."
	VCB_COMMON_SLIDER_BORDER = "테두리"
	VCB_COMMON_SLIDER_BORDER_TOOLTIP = "테두리 텍스처를 변경하려면 이 커서를 움직입니다."
	VCB_COMMON_SLIDER_BORDER_OPACITY = "테두리 불투명도"
	VCB_COMMON_SLIDER_BORDER_OPACITY_TOOLTIP = "테두리 불투명도를 변경하려면 이 커서를 움직입니다."
	VCB_COMMON_SLIDER_PADDING_H = "페딩 H"
	VCB_COMMON_SLIDER_PADDING_H_TOOLTIP = "이 커서를 움직여 버프의 수평 간격을 변경하십시오."
	VCB_COMMON_SLIDER_PADDING_V = "페딩 V"
	VCB_COMMON_SLIDER_PADDING_V_TOOLTIP = "이 커서를 움직여 버프의 수직 간격을 변경하십시오."
	VCB_COMMON_SLIDER_FONT_OFFSET_X = "폰트 옵셋 X"
	VCB_COMMON_SLIDER_FONT_OFFSET_X_TOOLTIP = "폰트의 수평 옵셋을 변경하려면 이 값을 이동하십시오."
	VCB_COMMON_SLIDER_FONT_OFFSET_Y = "폰트 옵셋 Y"
	VCB_COMMON_SLIDER_FONT_OFFSET_Y_TOOLTIP = "폰트의 세로 옵셋을 변경하려면 이 값을 이동하십시오."
	
	VCB_COMMON_EDITBOX_CUSTOM_BORDER_PATH = "사용자정의 테두리 경로:"
	VCB_COMMON_EDITBOX_CUSTOMFONT_PATH = "사용자정의 글꼴 경로:"
	
	VCB_COMMON_PAGE_1 = "페이지 2에 1"
	VCB_COMMON_PAGE_2 = "페이지 2에 2"
	
	VCB_CAT_GENERAL = "일반"
	VCB_CAT_CONSOLIDATED_ICON = "통합버프 아이콘"
	VCB_CAT_BUFF_FRAME = "버프 프레임"
	VCB_CAT_AURA = "아우라(버프)"
	VCB_CAT_AURA_TIMER = "아우라 타이머"
	VCB_CAT_BORDER = "테두리"
	VCB_CAT_ABOUT_1 = "VCB 란 무엇입니까?"
	VCB_CAT_ABOUT_2 = "누가 VCB를 만들었습니까?"
	VCB_CAT_ABOUT_3 = "특별 감사 :"
	VCB_CAT_ABOUT_4 = "한글 애드온 다운로드"
	
	VCB_ABOUT_TEXT_1 = "Vanilla Consolidate Buff-Frames (VCB)는 오라를 관리하는 스마트 시스템입니다. AddOn은 취향에 맞게 사용자 정의 할 수있는 많은 기능을 제공하며 더 낳은 개요를 위해 많은 유용한 기능을 추가합니다. 이는 처음부터 그 목적입니다."
	VCB_ABOUT_TEXT_2 = "VCB는 Kronos (Twinstar.cz)에서 AddOn을 개발 한 Shino (Albea) <Synced>가 제작했습니다. 그는 공식적으로 Twinstar 커뮤니티에서 Geigerkind로 알려져 있습니다."
	VCB_ABOUT_TEXT_3 = "Flynn (Twinstar AddOn Master) - 처음부터 도와 줘서 고마워. Schaka (Questie의 저자) - 처음부터 나를 도와 주셔서 감사합니다. Sinsthar (PowerAuras의 저자) - 당신은 나에게 인터페이스를 만드는 영감을주었습니다."
	VCB_ABOUT_TEXT_4 = "Moosic <Synced> - AddOn Fender <Synced> 테스트 - Areina의 초기 피드백 <Synced> -이 말을 도와주었습니다 ^^"
	VCB_ABOUT_TEXT_5 = "http://cafe.naver.com/vanillawow - again 길드"

	VCB_CUR_PROFILE_TEXT = "알수 없음"
	VCB_CONSOLIDATED_BUFFS_TEXT_1 = "야생의 징표"
	VCB_CONSOLIDATED_BUFFS_TEXT_2 = "야생의 선물"
	VCB_CONSOLIDATED_BUFFS_TEXT_3 = "신의 권능: 인내"
	VCB_CONSOLIDATED_BUFFS_TEXT_4 = "인내의 기원"
	VCB_CONSOLIDATED_BUFFS_TEXT_5 = "Divine Spirit"
	VCB_CONSOLIDATED_BUFFS_TEXT_6 = "Prayer of Spirit"
	VCB_CONSOLIDATED_BUFFS_TEXT_7 = "Shadow Protection"
	VCB_CONSOLIDATED_BUFFS_TEXT_8 = "Prayer of Shadow Protection"
	VCB_CONSOLIDATED_BUFFS_TEXT_9 = "Arcane Intellect"
	VCB_CONSOLIDATED_BUFFS_TEXT_10 = "Arcane Brilliance"
	VCB_CONSOLIDATED_BUFFS_TEXT_11 = "Greater Blessing of Sanctuary"
	VCB_CONSOLIDATED_BUFFS_TEXT_12 = "Greater Blessing of Kings"
	VCB_CONSOLIDATED_BUFFS_TEXT_13 = "Greater Blessing of Might"
	VCB_CONSOLIDATED_BUFFS_TEXT_14 = "Greater Blessing of Salvation"
	VCB_CONSOLIDATED_BUFFS_TEXT_15 = "Greater Blessing of Wisdom"
	VCB_CONSOLIDATED_BUFFS_TEXT_16 = "Greater Blessing of Light"
	VCB_CONSOLIDATED_BUFFS_TEXT_17 = "Trueshot Aura"
	
	VCB_WELCOME_TEXT = " 이제 로드되었습니다.! VCB를 구성하려면 /vcb 또는 /버프확장 명령을 사용하십시오!"
	VCB_HAS_BEEN_LOADED = " 로드되었습니다.!"
	VCB_HAS_BEEN_SAVED = " 저장 되었습니다.!"
	VCB_HAS_BEEN_REMOVED = " 제거 되었습니다.!"
	VCB_TEXT_PROFILE = "프로파일: "
	VCB_HAS_BEEN_CANCELLED = " 취소 되었습니다.!"
	VCB_HAS_BEEN_ADDED = " 추가 되었습니다.!"
	VCB_IS_ALREADY_IN_LIST = " 이미 목록에 있습니다.!"
	VCB_IS_NOT_IN_LIST = " 목록에 없습니다.!"
	VCB_CB_LIST_EMPTIED = "통합버프아이콘창의 목록이 비워졌습니다.!"
	VCB_BB_LIST_EMPTIED = "금지 된 버프 목록이 비워졌습니다.!"
	
	VCB_ABILITY_LOWER_SCRIPT_1 = "야생의 징표"
	VCB_ABILITY_LOWER_SCRIPT_2 = "야생의 선물"
	VCB_ABILITY_LOWER_SCRIPT_3 = "정조준 오라"
	VCB_ABILITY_LOWER_SCRIPT_4 = "상급 왕의 축복"
	VCB_ABILITY_LOWER_SCRIPT_5 = "왕의 축복"
	VCB_ABILITY_LOWER_SCRIPT_6 = "상급 힘의 축복"
	VCB_ABILITY_LOWER_SCRIPT_7 = "힘의 축복"
	VCB_ABILITY_LOWER_SCRIPT_8 = "상급 지혜의 축복"
	VCB_ABILITY_LOWER_SCRIPT_9 = "지혜의 축복"
	VCB_ABILITY_LOWER_SCRIPT_10 = "greater blessing of light"
	VCB_ABILITY_LOWER_SCRIPT_11 = "빛의 축복"
	VCB_ABILITY_LOWER_SCRIPT_12 = "greater blessing of salvation"
	VCB_ABILITY_LOWER_SCRIPT_13 = "blessing of salvation"
	VCB_ABILITY_LOWER_SCRIPT_14 = "신비한 지능"
	VCB_ABILITY_LOWER_SCRIPT_15 = "신비한 총명함"
	VCB_ABILITY_LOWER_SCRIPT_16 = "신의 권능: 인내"
	VCB_ABILITY_LOWER_SCRIPT_17 = "인내의 기원"
	VCB_ABILITY_LOWER_SCRIPT_18 = "divine spirit"
	VCB_ABILITY_LOWER_SCRIPT_19 = "prayer of spirit"
	VCB_ABILITY_LOWER_SCRIPT_20 = "암흑 보호"
	VCB_ABILITY_LOWER_SCRIPT_21 = "암흑 보호의 기원"
	VCB_TIMER_FRAME_SHOW_DISABLEUNIT_TOOLTIP = "타이머의 유닛을 제거하려면 이 옵션을 선택하십시오.(즉, m/s/h)"
	VCB_TIMER_FRAME_SHOW_DISABLEUNIT = "단위 제거" --Remove unit
	
	VCB_LOCKED_FRAMES = "프레임 잠금!"
	VCB_UNLOCKED_FRAMES = "프레임 잠금 해제!"
end

**Comment by tdymel** [comment]
Added
Thy!
