### ISSUE TITLE
"Change Color below 60's" Function Improper

### ISSUE THREAD

**Issue by ZetoxZ** [Geigerkind/VCB#8]
When the Timer > "Change Color Below 60's" is checked--the color incorrectly briefly flashes the color for durations over 60's and then goes back to it's proper value. 

Seems like the mod is doing color checks improperly. With each new buff it's checking every new buff as if it were a duration over 60's displaying that color;  then after that showing the "change color below 60's. 

Does this make sense?

**Comment by ZetoxZ** [comment]
Any buff (like a stance) will trigger the color to be set back to normal for a brief moment and then turn to "change color below 60's' color.

**Comment by tdymel** [comment]
Nvm me
