### ISSUE TITLE
Synchronous Flash Function 

### ISSUE THREAD

**Issue by ZetoxZ** [Geigerkind/VCB#9]
Great work on the timing! :)

Small last edit and it should be perfect; **the buffs and debuffs should flash ''in sync'' synchronously with one another.** 

Currently they all have separate flash timing dependent on when the buff is started meaning they all have their own separate 'flashing' timer. 

TBH: if you wanted you could even add this as a separate function of it's own option (synchronous flash vs separate flash), as it is kinda neat. I'm just a purist :)

Good luck and continue the good work :)

**Comment by tdymel** [comment]
Need to add another feature as well, anyway I guess^^
